comment:                  # this is a top-level key
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: false 
  require_base: false 
  require_head: true 
  hide_project_coverage: true