apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app
  labels:
    app: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-app
  template:
    metadata:
      labels:
        app: recipe-app
    spec:
      containers:
        - name: recipe-container
          image: recipe-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8501
          env:
            - name: STREAMLIT_HOST
              value: "recipe-service.default.svc.cluster.local"
