name: Build and Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker to use Minikube
        run: |
          eval $(minikube -p minikube docker-env)

      - name: Delete existing CouchDB
        run: |
          helm delete couchdb -n couchdb || true

      - name: Install CouchDB with Helm
        run: |
          helm install \
          couchdb \
          --version 4.5.3 \
          --set couchdbConfig.couchdb.uuid=decafbaddecafbaddecafbaddecafbad \
            couchdb/couchdb \
          --namespace couchdb

      - name: Get credentials
        run: |
          export COUCH_USERNAME=$(kubectl get secret --namespace couchdb couchdb-couchdb -o jsonpath="{.data.adminUsername}" | base64 --decode)
          export COUCH_PASSWORD=$(kubectl get secret --namespace couchdb couchdb-couchdb -o jsonpath="{.data.adminPassword}" | base64 --decode)
          export COUCH_URL=http://localhost:5984
          export COUCH_PORT=5984

      - name: Wait for CouchDB to be ready
        run: |
          sleep 3
          kubectl wait --for=condition=ready pod -l app=couchdb -n couchdb --timeout=600s
          kubectl port-forward svc/couchdb-svc-couchdb -n couchdb 5984:5984 &
          sleep 2

      - name: Set up databases
        run: make init_db

      - name: Take down port-forwarding
        run: |
          killall kubectl || true
          export COUCH_URL=http://couchdb-svc-couchdb.couchdb.svc.cluster.local

      - name: Take down previous deployments
        run: |
          kubectl delete deployment recipe-app -n recipe-app || true
          kubectl delete service recipe-app -n recipe-app || true

      - name: Delete previous docker images
        run: |
          docker rmi recipe-app:latest || true

      - name: Build Docker image with environment variables for CouchDB
        run: docker build --build-arg COUCH_USER=$COUCH_USERNAME --build-arg COUCH_PASSWORD=$COUCH_PASSWORD -t recipe-app:latest .

      - name: Apply Kubernetes configuration
        run: kubectl apply -f k8s/recipe_app/deployment.yaml -f k8s/recipe_app/service.yaml -n recipe-app

      - name: Wait for deployment to be ready
        run: |
          sleep 3
          kubectl wait --for=condition=available --timeout=600s deployment/recipe-app -n recipe-app

      - name: Expose application
        run: nohup kubectl port-forward svc/recipe-service -n recipe-app 8080:8501 > port-forward.log 2>&1 &
