name: Build and Deploy

on:
  push:
    # tags:
    #   - "v*"
    branches:
      - "**"

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker to use Minikube
        run: |
          eval $(minikube -p minikube docker-env)

      - name: Delete existing CouchDB Secret
        run: |
          kubectl delete secret couchdb-secret

      - name: Delete existing CouchDB
        run: |
          helm delete couch-db

      - name: Create CouchDB Secret
        run: |
          kubectl create secret generic couchdb-secret \
           --from-literal=adminUsername=${{ secrets.COUCH_USER }} \
           --from-literal=adminPassword=${{ secrets.COUCH_PASSWORD }} \
           --from-literal=cookieAuthSecret=${{ secrets.COUCH_COOKIE_AUTH_SECRET }}

      - name: Install CouchDB with Helm
        run: |
          helm install \
          couch-db \
          --version 4.5.3 \
          --set createAdminSecret=false \
          --set couchdbConfig.couchdb.uuid=decafbaddecafbaddecafbaddecafbad \
            couchdb/couchdb \
          --namespace default
