name: Build and Deploy

on:
  push:
    # tags:
    #   - "v*"
    branches:
      - "**"

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker to use Minikube
        run: |
          eval $(minikube -p minikube docker-env)

      - name: Delete existing CouchDB
        run: |
          helm delete couchdb || true

      - name: Install CouchDB with Helm
        run: |
          helm install \
          couchdb \
          --version 4.5.3 \
          --set couchdbConfig.couchdb.uuid=decafbaddecafbaddecafbaddecafbad \
            couchdb/couchdb \
          --namespace default

      - name: Get credentials
        run: |
          export COUCH_USER=$(kubectl get secret --namespace default couchdb-couchdb -o jsonpath="{.data.adminUsername}" | base64 --decode)
          export COUCH_PASSWORD=$(kubectl get secret --namespace default couchdb-couchdb -o jsonpath="{.data.adminPassword}" | base64 --decode)
          export COUCH_URL=http://couchdb-svc-couchdb.couchdb.svc.cluster.local
          export COUCH_PORT=5984

      - name: Delete previos docker images
        run: |
          docker rmi recipeApp:latest || true

      - name: Build Docker image with environment variables for CouchDB
        run: docker build \
          --build-arg COUCH_USER=$COUCH_USER \
          --build-arg COUCH_PASSWORD=$COUCH_PASSWORD \
          -t recipe-app .

      - name: Apply Kubernetes configuration
        run: kubectl apply -f k8s/recipe_app/deployment.yaml -f k8s/recipe_app/service.yaml

      - name: Wait for deployment to be ready
        run: kubectl wait --for=condition=available --timeout=600s deployment/recipe-app

      - name: Run health check
        run: kubectl port-forward svc/recipe-app 5981:80 & \
          sleep 5 && \
          curl -s http://localhost:5981/_up | grep "true"
