name: Build and Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Take down port-forwarding
        run: |
          killall kubectl || true
          export COUCH_URL=http://couchdb-svc-couchdb.couchdb.svc.cluster.local

      - name: Take down previous deployments
        run: |
          kubectl delete deployment recipe-app -n recipe-app || true
          kubectl delete service recipe-service -n recipe-app || true

      - name: Build Docker image with environment variables for CouchDB
        env:
          COUCHDB_USERNAME: ${{ secrets.COUCHDB_USERNAME }}
          COUCHDB_PASSWORD: ${{ secrets.COUCHDB_PASSWORD }}
        run: |
          eval $(minikube -p minikube docker-env)
          docker rmi recipe-app:latest || true
          docker build \
            --build-arg COUCH_USER=${{ secrets.COUCHDB_USERNAME }} \
            --build-arg COUCH_PASSWORD=${{ secrets.COUCHDB_PASSWORD }} \
            -t recipe-app:latest .

      - name: Apply Kubernetes configuration
        run: kubectl apply -f k8s/recipe_app/deployment.yaml -f k8s/recipe_app/service.yaml -n recipe-app

      - name: Wait for deployment to be ready
        run: |
          sleep 3
          kubectl wait --for=condition=available --timeout=600s deployment/recipe-app -n recipe-app

      - name: Expose application
        run: nohup kubectl port-forward svc/recipe-service -n recipe-app 8080:8501 > port-forward.log 2>&1 &
