name: CI Pipeline
on:
  push:
  pull_request:
    branches:
      - "**"

jobs:
  lint-format:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff Lint
        run: ruff check app/

      - name: Run Ruff Lint
        run: ruff format app/

  test:
    runs-on: self-hosted
    needs: lint-format

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: expose variables
        run: echo "COUCH_USER=${{ secrets.COUCH_USER }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          COUCH_URL: ${{ vars.COUCH_URL }}
          COUCH_PORT: ${{ vars.COUCH_PORT }}
          RUN_ENV: ${{ vars.RUN_ENV}}
          COUCH_USER: ${{ secrets.COUCH_USER }}
          COUCH_PASSWORD: ${{ secrets.COUCH_PASSWORD }}
        run: |
          # Port forward couchdb for tests
          kubectl port-forward svc/couchdb-svc-couchdb -n couchdb 5984:5984 & 
          pytest --cov --junitxml=junit.xml -o junit_family=legacy

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
