name: Pre-Build Validation

on:
  push:
    paths:
      - "**.py"
      - "**.yml"
      - "**.yaml"
      - "**.json"
      - "**/requirements.txt"
    branches:
      - "**"

jobs:
  lint:
    name: Lint Code
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache Ruff
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-ruff-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-ruff-

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff Lint
        run: ruff check app/ --show-source --exit-zero

  secrets-scan:
    name: Scan for Secrets
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown

  badges:
    name: Update Status Badges
    needs: [lint, secrets-scan]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Badges
        run: |
          LINT_STATUS=${{ needs.lint.result == 'success' && 'passing' || 'failing' }}
          SECRETS_STATUS=${{ needs.secrets-scan.result == 'success' && 'passing' || 'failing' }}

          BADGES="[![Lint Status](https://img.shields.io/badge/Lint-$LINT_STATUS-brightgreen?style=flat-square)]() [![Secrets Scan Status](https://img.shields.io/badge/Secrets-$SECRETS_STATUS-brightgreen?style=flat-square)]()"

          sed -i '/<!-- Badges -->/c\<!-- Badges -->\n$BADGES' README.md

      - name: Commit and Push Updates
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update status badges"
          git push
